version: '3.3'

services:
  app:
    tty: true
    build: './'
    environment:
      - REDIS_URL=redis://redis:6379
    ports:
      - '25566:25565'
  redis:
    image: 'redis:alpine'
    ports:
      - '6379'
    volumes:
      - mcid_redis_data:/data
volumes:
  mcid_redis_data:
